### PR TITLE
Subsets

### PR DESCRIPTION
**Pull request by rmflight**
This pull request makes it possible to only use a subset of the `consultthat` features, as well as add those features to an already existing project.

I also changed it to use roxygen to generate the NAMESPACE, and added some imports, and started adding some testing

### CODE REVIEW

**Comment by stephstammel** [comment]
Thankyou Robert this is brilliant! Sorry I've been slow here, moved 500km yesterday. I hope to be back at this next week.
		
		

		Steph de Silva, Ph.D.Founder, Rex Analytics+61 414 943 245steph@rex-analytics.comwww.rex-analytics.com

	




On Sat, May 12, 2018 at 6:24 AM +1000, "Robert M Flight" <notifications@github.com> wrote:












This pull request makes it possible to only use a subset of the consultthat features, as well as add those features to an already existing project.


I also changed it to use roxygen to generate the NAMESPACE, and added some imports, and started adding some testing



You can view, comment on, or merge this pull request online at:


  https://github.com/stephdesilva/consultthat/pull/3

Commit Summary

  using roxygen to create namespace, and doing it on install
  actually importing usethis create_package
  fixing a little bug that made roxygen complain
  cleaning up the createProject function to be able to provide the full directory as the first argument, and then selectively write only certain directories, and overwrite if necessary
  using walk to actually write the directories
  using rprojroot to find the project directory, and just using some direct variables from the time log file
  enable markdown for Roxygen
  some basic testing on creating a project
  shorter named overwrite variable, and checking if the directory is empty or not
  updating documentation


File Changes

  
    M
    DESCRIPTION
    (8)
  
  
    M
    NAMESPACE
    (16)
  
  
    M
    R/createProject.R
    (120)
  
  
    M
    R/punchOff.R
    (2)
  
  
    M
    R/punchOn.R
    (25)
  
  
    M
    consultthat.Rproj
    (1)
  
  
    M
    man/addIssue.Rd
    (5)
  
  
    M
    man/closeIssue.Rd
    (5)
  
  
    M
    man/createProject.Rd
    (17)
  
  
    M
    man/punchOff.Rd
    (3)
  
  
    M
    man/punchOn.Rd
    (7)
  
  
    A
    tests/testthat.R
    (4)
  
  
    A
    tests/testthat/full_files
    (0)
  
  
    A
    tests/testthat/test-createproject.R
    (18)
  
  
    A
    tests/testthat/time_files
    (0)
  


Patch Links:

  https://github.com/stephdesilva/consultthat/pull/3.patch
  https://github.com/stephdesilva/consultthat/pull/3.diff

**Comment by rmflight** [comment]
You are fine Steph. I noticed tweets about moving, and I know it's the weekend already in the land of Oz.

Should wait anyways, the timekeeping fails if it's not an actual package. Was thinking of using `project_documents` directory as the way to find the root of the project folder, so can use this with non package project directories as well.

**Comment by rmflight** [comment]
Alternatively, we could have a `.consultthat` file in the directory, and it would have the documents directory path in it. That way people could use whatever they wanted.

**Comment by stephstammel** [comment]
This was actually the issue I felt was the biggest weakness of the whole concept - the fact that as written, it needs to be a start-from-scratch and had to be written up as a package. That’s sometimes overkill for small projects/ people starting out for whom this is probably most useful.

I really like the idea of a .consultthat file which could manage these sorts of things and provide a better array of flexibility. The ‘one size fits kind of a few people’ approach is limited :)

(I’ve gotten us into the house - mostly - now. It was a 500km move from a 35 ha farm into a tiny inner city terrace. Some culture shock going on around here ;) )



Steph de Silva, Ph.D.

Founder, Rex Analytics
+61 414 943 245
steph@rex-analytics.com <mailto:steph@rex-analytics.com>
www.rex-analytics.com <http://www.rex-analytics.com/>

**Pull request merged**
